name: Publish to NuGet
permissions:
  contents: read
  packages: write
on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Build
      run: |
        cd Paywire.NET
        dotnet restore
        dotnet build --configuration Release --no-restore

    - name: Test
      run: | 
        cd Paywire.NET.Tests
        dotnet test
      env: 
        PWCLIENTID: ${{ secrets.PWCLIENTID }}
        PWUSER: ${{ secrets.PWUSER }}
        PWKEY: ${{ secrets.PWKEY }}
        PWPASS: ${{ secrets.PWPASS }}        

    - name: Pack
      run: |
        cd Paywire.NET
        # Use GitHub Run Number as the Build number in the version
        dotnet pack --configuration Release --no-restore --output nupkg /p:Version=1.0.0.${{ github.run_number }}

    - name: Push to NuGet
      run: |
        cd Paywire.NET
        dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
